import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import React, { useState } from "react";
import Hero from "../components/Hero";
import CtaHead from "../components/CtaHeader";
import Cta from "../components/Cta";
import Services from "../components/Services";
import AboutUs from "../components/AboutUs";
import Footer from "../components/Footer";
import Testimonial from "../components/Testimonial";
import Team from "../components/Team";
import styled from "styled-components";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  const toggle = () => {
    setIsOpen(!isOpen);
  };

  const WpBtn = styled.button`
    position: fixed;
    bottom: 30px;
    right: 20px;
    display: flex;
    flex-direction: column;
    &:hover {
      cursor: pointer;
    }
  `;
  return (
    <div className="scroll-smooth scrollbar-hide relative">
      <Head>
        <title>Genesys Global</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar isOpen={isOpen} toggle={toggle} />
      <Navbar toggle={toggle} />
      <Hero />
      <div className="relative ">
        <CtaHead />
        <AboutUs />
        <Cta />
        <Testimonial />
        <Services />
        <Team />
        <Footer />
      </div>
      <WpBtn>
        <Link href="https://wa.me/919082939164" passHref >
          <Image
            src={"/wp.svg"}
            width={40}
            height={40}
            layout="intrinsic"
            alt="wp"
            className="mt-2"
          />
        </Link>
        <div className="h-2"></div>
        <Link href="tel:+919082939164" passHref >
          <Image
            src={"/tl.svg"}
            width={40}
            height={40}
            layout="intrinsic"
            alt="tl"
            className="mt-2"
          />
        </Link>
      </WpBtn>
    </div>
  );
}
